CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS merch (
    id            INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name          TEXT UNIQUE NOT NULL,
    cost          INTEGER
);

CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    coins INTEGER CONSTRAINT coins_value CHECK (coins >= 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS coin_history (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    from_user INTEGER REFERENCES "user" (id) ON DELETE SET NULL,
    to_user INTEGER REFERENCES "user" (id) ON DELETE SET NULL,
    amount INTEGER CONSTRAINT amount_value CHECK (amount > 0) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    merch_id INTEGER REFERENCES merch (id) ON DELETE SET NULL,
    user_id INTEGER REFERENCES "user" (id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);